version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      # You will need to expose these port to the public
      - "80:80"
      - "443:443"
    links:
      - v2ray:v2ray # This is very important step, that the nginx docker need this to coonect with v2ray docker
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: v2ray -config=/etc/v2ray/config.json
    volumes:
      - ./data/v2ray:/etc/v2ray
      - ./logs/v2ray:/var/log/v2ray
    expose:
      - "30909" # This is for the nginx docker, you don't need to expose it to the public
